---
# tasks file for ansible-ntp

- name: Variables for OS
  include_vars: "{{ ansible_os_family }}.yml"

- name: Installing NTP...
  package:
    name: ntp
    state: present

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Enabling NTP in boot
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes

- name: Red Hat | Configuring NTP service
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart ntpd  
  when: ansible_os_family == 'RedHat'

- name: Debian | Configuring NTP service
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart ntp 
  when: ansible_os_family == 'Debian'
